spring.application.name=leadmanagement

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/leadmanagement
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.css=/swagger-ui/custom.css
